apiVersion: v1
kind: Secret
metadata:
  name: nexus-registry-secret
type: kubernetes.io/dockerconfigjson
data:
#  .dockerconfigjson: "YWRtaW46TmV4dXNAMTIz"
 .dockerconfigjson: eyJhdXRocyI6eyJodHRwOi8vMTkyLjE2OC4xLjIxOjgwODMvcmVwb3NpdG9yeS9kb2NrZXItaG9zdGVkIjp7InVzZXJuYW1lIjoiYWRtaW4iLCJwYXNzd29yZCI6Ik5leHVzQDEyMyIsImVtYWlsIjoiYWJjQGdtYWlsLmNvbSIsImF1dGgiOiJZV1J0YVc0NlRtVjRkWE5BTVRJeiJ9fX0=
#  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSIxOTIuMTY4LjEuMjE6ODA4MyI6IHsKCQkJImF1dGgiOiAiWVdSdGFXNDZUbVY0ZFhOQU1USXoiCgkJfQoJfQp9
#  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJsb2NhbGhvc3Q6ODA4MyI6IHsKCQkJImF1dGgiOiAiWVdSdGFXNDZUbVY0ZFhOQU1USXoiCgkJfQoJfQp9