name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven

      - name: Build JAR
        run: |
          mvn clean install -DskipTests=true

      - name: SonarQube Analysis
        run: |
          mvn sonar:sonar -Dsonar.host.url=http://localhost:9000 -Dsonar.login=$SONARQUBE_TOKEN

      - name: Login to Docker Hub
        run: |
          docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD

      - name: Build and Push Docker Image
        run: |
          docker build -t myapp:latest .
          docker tag myapp:latest $DOCKERHUB_USERNAME/myapp:latest
          docker push $DOCKERHUB_USERNAME/myapp:latest

      - name: Push Docker Image to Nexus
        run: |
          docker login -u $NEXUS_USERNAME -p $NEXUS_PASSWORD http://localhost:8083/repository/docker-hosted/
          docker push myapp:latest
